// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTTvdvph-5qrzNdBCNpzVQRMXurxrsbY',
    appId: '1:341699863338:web:2c5a0f5e3c1b0983717453',
    messagingSenderId: '341699863338',
    projectId: 'proj-ad673',
    authDomain: 'proj-ad673.firebaseapp.com',
    storageBucket: 'proj-ad673.appspot.com',
    measurementId: 'G-CHS89GS9E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3LutniyHrBqWn-yoHkwnZm5W13jpIf6I',
    appId: '1:341699863338:android:8ca73e7aec63e036717453',
    messagingSenderId: '341699863338',
    projectId: 'proj-ad673',
    storageBucket: 'proj-ad673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9gy8MqlTCHitqwlE-9cRm2VLOvMElbak',
    appId: '1:341699863338:ios:5efdddb4793bba84717453',
    messagingSenderId: '341699863338',
    projectId: 'proj-ad673',
    storageBucket: 'proj-ad673.appspot.com',
    iosClientId: '341699863338-kua0hioe10mtifv6cv812mdn4gb7k6gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23B5lProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9gy8MqlTCHitqwlE-9cRm2VLOvMElbak',
    appId: '1:341699863338:ios:5efdddb4793bba84717453',
    messagingSenderId: '341699863338',
    projectId: 'proj-ad673',
    storageBucket: 'proj-ad673.appspot.com',
    iosClientId: '341699863338-kua0hioe10mtifv6cv812mdn4gb7k6gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23B5lProject',
  );
}
