// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0yZxXgS_qcbsu4oRcJn6J1aZeLdAnZSA',
    appId: '1:582484773027:web:a2e7db94504a9528a55716',
    messagingSenderId: '582484773027',
    projectId: 'discussion-5f707',
    authDomain: 'discussion-5f707.firebaseapp.com',
    storageBucket: 'discussion-5f707.appspot.com',
    measurementId: 'G-C5MRPQ8BV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABzz5jfWci6618-zi0bxrO3-QSVQw4ELc',
    appId: '1:582484773027:android:da7ef114db332cb2a55716',
    messagingSenderId: '582484773027',
    projectId: 'discussion-5f707',
    storageBucket: 'discussion-5f707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8jfr9ftVWDZTbpoZ1FjLr_FGk6PRKWy4',
    appId: '1:582484773027:ios:3d4caf2b7a0788c0a55716',
    messagingSenderId: '582484773027',
    projectId: 'discussion-5f707',
    storageBucket: 'discussion-5f707.appspot.com',
    iosClientId: '582484773027-104ungtinleajhe2ta1is8abm4h9g11j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23B5lProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8jfr9ftVWDZTbpoZ1FjLr_FGk6PRKWy4',
    appId: '1:582484773027:ios:3d4caf2b7a0788c0a55716',
    messagingSenderId: '582484773027',
    projectId: 'discussion-5f707',
    storageBucket: 'discussion-5f707.appspot.com',
    iosClientId: '582484773027-104ungtinleajhe2ta1is8abm4h9g11j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23B5lProject',
  );
}
