// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBAZ8W9bn7UVbfdl87KiREmpnRxoaLfFk',
    appId: '1:241482224830:web:e8bc78982cc18f90ae3aef',
    messagingSenderId: '241482224830',
    projectId: 'cmsc23-b5l-project',
    authDomain: 'cmsc23-b5l-project.firebaseapp.com',
    storageBucket: 'cmsc23-b5l-project.appspot.com',
    measurementId: 'G-LDGEZTBMMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2ahqbxiudTXzXliUtV9pmIpprAql3ks',
    appId: '1:241482224830:android:f67a83fc75dbb31eae3aef',
    messagingSenderId: '241482224830',
    projectId: 'cmsc23-b5l-project',
    storageBucket: 'cmsc23-b5l-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxRtJQjKaS9ihBhYeVP3pSoHbgaVtZIY0',
    appId: '1:241482224830:ios:540b51c4dffee0d6ae3aef',
    messagingSenderId: '241482224830',
    projectId: 'cmsc23-b5l-project',
    storageBucket: 'cmsc23-b5l-project.appspot.com',
    iosClientId: '241482224830-vreq03apmvpljn58ei4tbftncsl3tsjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23B5lProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxRtJQjKaS9ihBhYeVP3pSoHbgaVtZIY0',
    appId: '1:241482224830:ios:540b51c4dffee0d6ae3aef',
    messagingSenderId: '241482224830',
    projectId: 'cmsc23-b5l-project',
    storageBucket: 'cmsc23-b5l-project.appspot.com',
    iosClientId: '241482224830-vreq03apmvpljn58ei4tbftncsl3tsjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23B5lProject',
  );
}
